[workspace]
resolver = "2"
members = [ "testcode", "testreactor", "wasm-to-scratch", "buddy_block", "depict_nums"]
default-members = ["wasm-to-scratch"]

[workspace.package]
# license = "MIT/Apache-2.0"
license = "LGPL-3.0"
edition = "2021"
rust-version = "1.75"
version = "0.1.0"

